#!/bin/bash
#
# Usage: runtest files...
#
# Run Tao test documents. capture.xl is automatically pre-loaded.
# If file name ends in .xl, its content is wrapped in capture_begin/capture_end
# before being loaded in Tao. Otherwise, the file is loaded as is.
#
# Examples:
#   run_test.sh all.ddd
#   run_test.sh t_anaglyph.xl

. functions.sh

# Set path to the Tao Presentations executable
: ${ENV_FILE:="$HOME/.tao_tests_env"}
if [ "$ENV_FILE" -a -r "$ENV_FILE" ] ; then
  . "$ENV_FILE"
else
  # Defaults
  case $(uname) in
    Darwin)
      TAO="$HOME/work/tao/install/Tao Presentations.app/Contents/MacOS/Tao Presentations"
      ;;
    Linux)
      export LD_LIBRARY_PATH="$HOME/work/tao/install"
      TAO="$HOME/work/tao/install/Tao"
      ;;
    MINGW*)
      TAO="$HOME/work/tao/install/Tao"
      ;;
esac
fi

[ "$@" ] || die "No file"

# Default values for environment variables
[ "$CAPTURE_DIR" ] || export CAPTURE_DIR=out

[ -e "$CAPTURE_DIR" ] || mkdir -p "$CAPTURE_DIR"

WRAPFILE=""
# If $1 is a .xl file, create a .ddd file that can be run by itself
wrap_xl_file() {
  case "$1" in
    *.xl)
      WRAPFILE=$(_mktemp $1.XXXX)
      cat >$WRAPFILE <<_EOF_
// Generated by run_test.sh
capture_begin
import "$1"
capture_end
_EOF_
      ;;
  esac
}

# Remove file previously created by wrap_xl_file
clean_wrap_file() {
  [ "$WRAPFILE" ] || return 0
  rm -f "$WRAPFILE"
  WRAPFILE=""
}

for f in "$@" ; do
  wrap_xl_file $f
  [ "$WRAPFILE" ] && f="$WRAPFILE"
  "$TAO" -nosplash -p capture.xl $f
  clean_wrap_file
done
